#!/bin/bash
set -e

cargo build --release --features generate --locked --target-dir target
scripts/mkmo locale/
strip target/release/nali

tar --zstd -cf nali.tar.zst man completions paru.conf locale -C target/release nali

